const sections = [
  {
    title: '1. Display Commands (D)',
    subtitle: 'These commands are used to display the status of system resources, jobs, consoles, and configuration.',
    headers: ['Command', 'Description'],
    rows: [
      ['D A,L', 'Displays active users (TSO), started tasks, jobs, and regions.'],
      ['D A,<TASK NAME>', 'Shows whether a specific started task is active or not.'],
      ['D ASM', 'Displays the usage of the Auxiliary Storage Manager.'],
      ['D C', 'Displays the consoles (Master and other consoles).'],
      ['D C,B', 'Displays the console buffer.'],
      ['D C,K', 'Displays the list of control command operands.'],
      ['D C,M', 'Displays the Master Console.'],
      ['D C,N', 'Displays information about inactive consoles.'],
      ['D D', 'Displays the dump data sets (e.g., SYS1.DUMPxx).'],
      ['D D,T', 'Displays the dump data sets with their titles.'],
      ['D DUMP', 'Displays the status of dump data sets.'],
      ['D ETR', 'Displays External Time Reference (ETR) status.'],
      ['D GRS,C', 'Displays system contention (Global Resource Serialization).'],
      ['D IPLINFO', 'Displays current IPL (Initial Program Load) information.'],
      ['D J', 'Displays active jobs.'],
      ['D J,L', 'Displays system activity / active jobs.'],
      ['D OPDATA', 'Displays the command prefixes of DB2, JES, RACF, etc. regions.'],
      ['D PFK', 'Displays commands defined for Program Function Keys (PFKs).'],
      ['D R,L', 'Displays outstanding system requests (WTORs).'],
      ['D R,R', 'Displays pending action messages.'],
      ['D R,U', 'Displays the number of devices requiring attention or with unfulfilled mount requests.'],
      ['D SMF', 'Displays the SMF (System Management Facility) data sets (e.g., SYS1.MANx).'],
      ['D SMF,O', 'Displays the current SMF options.'],
      ['D SMF,S', 'Displays the SMF status.'],
      ['D T or DT', 'Displays the local time of the system, GMT time, Julian date, and date.'],
      ['D TS,L', 'Displays active TSO users.'],
      ['D XCF', 'Displays systems in the Sysplex.'],
      ['D XCF,COUPLE', 'Displays the current coupling facility information.'],
      ['D A,L,USERID=<ID>', 'Display active jobs for a specific TSO userid'],
      ['D OMVS', 'Display whether OMVS is active'],
      ['D OMVS,F', 'Display mounted file systems'],
      ['D OMVS,OPTIONS', 'Display OMVS options'],
      ['D XCF,STR', 'Lists the coupling facility structures'],
      ['D XCF,STRNAME=<NAME>', 'Display info about an individual structure'],
      ['D SSI', 'Display the configured subsystems'],
      ['D GRS,RES=(*)', 'Display what resources you can view'],
      ['D GRS,RES=(SYSDSN)', 'Display enqueues on SYSDSN resources'],
      ['D GRS,E,C', 'List the resource everyone is waiting on'],
      ['$D PROCLIB', 'Display the system proclib'],
      ['SE \'<message>\'', 'Send a message to all TSO users (announcement)'],
      ['D A,<jobname>', 'Display information for a specific job (* is wildcard)'],
      ['D C,*', 'Display console info for the console where command was entered'],
      ['D C,A,CA', 'Display active sysplex consoles'],
      ['D C,N,CA', 'Display inactive sysplex consoles'],
      ['D GRS,RES(*,<dsn>)', 'Display contention with a specific dataset'],
      ['D IOS,CONFIG', 'Display I/O related configuration'],
      ['D J,A', 'Display detailed information of active jobs'],
      ['D M=CONFIG(<n>)', 'Display any deviation from requested configuration'],
      ['D NET,CPCP', 'Display the CP-CP session status'],
      ['D R,L,CN=(ALL)', 'Display outstanding replies from all consoles'],
      ['D U,DASD,<nnn>,<n>', 'Display a specific DASD unit and range'],
    ],
  },
  {
    title: '2. Console Control Commands (K)',
    subtitle: 'Console control commands manage console characteristics, message roll/delete modes, PFK definitions, and clear console buffers.',
    headers: ['Command', 'Description'],
    rows: [
      ['K E,*', 'Deletes the line marked with an asterisk (*) on the console.'],
      ['K E,X,Y', 'Deletes lines X through Y in the console.'],
      ["K N,PFK=(X,CMD='XXXXXXXX'),CON=N", "Defines a Program Function Key (PFK) where X is the key number and 'XXXXXXXX' is the command."],
      ['K Q', 'Clears the console buffer spool.'],
      ['K Q,L=<CONSOLE ID>', 'Clears a buffer shortage for a specific console ID.'],
      ["K S,DEL=RD", "Sets 'Roll Delete Mode' (the most common console message mode)."],
      ['K S,DEL=N', 'Stops message scrolling on the console.'],
      ['K S,REF', 'Displays the current console mode.'],
      ['K V,LEVEL=ALL', 'Displays all message traffic routed to the console.'],
      ['K V,LEVEL=I', 'Displays immediate action messages at the console.'],
      ['K V,LEVEL=R', 'Displays WTORs (Write-to-Operator with Reply) at the console.'],
      ['K V,REF', 'Displays all vary definitions.'],
      ['K A,REF', 'Shows areas on operator console'],
      ['K A,NONE', 'Remove "out of line area" from console (may need K E,D first)'],
      ['K A,14', 'Make the area 14 lines deep'],
      ['K A,6,6', 'Make two areas A and B, use D A,L,L=B to display in window B'],
      ['K D,F', 'Scroll forward (PF8 may also do this)'],
      ['K E,D', 'Remove the bottom "out of line display" area'],
      ['K E', 'Clear the scrolling messages from the screen'],
      ['K E,N', 'Remove nth message from the top of the screen'],
      ["K N,PFK=(001,CMD='d a,l;d ts,l')", 'Set PF key 001 to multiple commands separated by ;'],
      ['K E,SEG', 'Delete content of a message segment'],
      ['K E,1', 'Delete line 1 on the console'],
      ['PA1', 'Retrieve previous command'],
      ['K K', 'Clear screen of all messages except highlighted messages'],
      ['K C,A,0-999999999', 'Clear all messages from the console'],
      ['K D,PFK', 'Display program function key line'],
      ['K M,MILM=<n>', 'Change number of allowed WTO/WTOR message buffers'],
      ['K S,DEL=Y', 'Set console to delete all messages'],
      ['K S,DEL=R', 'Set console to roll all messages'],
      ['K S,RNUM=<n>', 'Set number of messages to roll when DEL=R or RD'],
      ['K S,RTME=<n>', 'Set roll interval in seconds when DEL=R or RD'],
      ['K T', 'Display time interval for dynamic display update'],
      ['K T,UTKE,<n>', 'Update dynamic display every n seconds'],
    ],
  },
  {
    title: '3. Vary Commands (V)',
    subtitle: 'Vary commands change the status of devices, paths, lines, and console options.',
    headers: ['Command', 'Description'],
    rows: [
      ['V DEV NUM,ONLINE', 'Varies a device online using its device number.'],
      ['V DEV NUM,OFFLINE', 'Varies a device offline using its device number.'],
      ['V NET,ID=LINE ID,ACT,ALL', 'Activates a network line.'],
      ['V NET,ID=LINE ID,INACT,F', 'Deactivates a network line (force).'],
      ['V NET,ID=<ID NAME>,ACT/INACT', 'Changes the status of the network resource to active or inactive.'],
      ['V NET,ID=<ID NAME>,ACT/INACT,SCOPE=ALL/ONLY', 'Changes the status of the network resource and its subordinate resources.'],
      ['V PATH(XXX,YY),ONLINE', 'Varies a channel path online (where XXX is device, YY is path).'],
      ['V PATH(XXX,YY),OFFLINE', 'Varies a channel path offline.'],
      ['V SMS,LIB(ATL NAME),ONLINE', 'Varies an Automated Tape Library (ATL) online.'],
      ['V SMS,LIB(ATL NAME),OFFLINE', 'Varies an Automated Tape Library (ATL) offline.'],
      ['V XXX,ONLINE', 'Varies a tape drive online (where XXX represents the drive address).'],
      ['V XXX,OFFLINE', 'Varies a tape drive offline.'],
      ['RO *ALL,V XXX,OFFLINE', 'Varies a drive offline across all systems in a Sysplex environment.'],
      ['RO *ALL,V <addr>,ONLINE', 'Vary a drive online on all systems in sysplex'],
      ['CF CHP(<cc>),ONLINE', 'Make a channel path online (Coupling Facility)'],
      ['CF CHP(<cc>),OFFLINE', 'Make a channel path offline'],
      ['V <n>,CONSOLE', 'Vary a device as a console'],
      ['V <n>,MSTCONS', 'Switch the master console to a device'],
      ['V <n>,OFFLINE,FORCE', 'Force a device offline (requires reply YES)'],
      ['V CH(<nn>),ONLINE', 'Vary a single channel online'],
      ['V PATH(<nnn>,<cc>),OFFLINE,UNCOND', 'Force a path offline unless it is the last path to an allocated device'],
    ],
  },
  {
    title: '4. Matrix Commands (D M)',
    subtitle: 'Matrix commands display physical configuration details, paths, and status of CPU/hardware components.',
    headers: ['Command', 'Description'],
    rows: [
      ['D M', 'Displays the configuration of the system.'],
      ['D M=CPU or D M=CPU,d m=core', 'Displays the CPU and core status.'],
      ['D M=DEV', 'Displays all paths to all devices.'],
      ['D M=DEV(DEVICE NAME)', 'Displays paths for a particular device.'],
      ['D M=CHP(CHIP ID)', 'Displays paths on a particular channel path (CHP).'],
      ['D M=STOR', 'Displays storage configuration.'],
      ['DS P,<ddd>,<nn>', 'Display device status and path info (checks each device)'],
    ],
  },
  {
    title: '5. DASD and Tape Display Commands',
    subtitle: 'Specific display commands for Direct Access Storage Devices (DASD) and tape drives.',
    headers: ['Command', 'Description'],
    rows: [
      ['D U,DASD,ONLINE,C00,8', 'Displays online DASD volumes starting at address C00 for a range of 8 devices.'],
      ['D U,TAPE,ONLINE', 'Displays tape drives online to the system.'],
      ['D U,TAPE,OFFLINE', 'Displays tape drives offline to the system.'],
      ['D U,,ALLOC,XXX,1', 'Displays the jobs allocated to a specific device XXX.'],
      ['D SMS,LIB(ALL),DETAIL', 'Displays details of Automated Tape Libraries (ATLs) available in the system.'],
      ['D SMS,LIB(ALL),STATUS', 'Displays status of Automated Tape Libraries (ATLs) in the system.'],
      ['D SMS,STORGRP(ALL),LISTVOL', 'Displays the storage groups and their associated volumes.'],
    ],
  },
  {
    title: '6. DFHSM (Hierarchical Storage Manager) Commands',
    subtitle: 'DFHSM commands manage backup, migration, recall, and space management.',
    headers: ['Command', 'Description'],
    rows: [
      ['F DFHSM,LIST USER', 'Lists authorized users of DFHSM.'],
      ['F DFHSM,LIST MVOL', 'Lists migration volumes.'],
      ['F DFHSM,Q ACT', 'Displays active DFHSM queries/tasks.'],
      ['F DFHSM,Q AC W', 'Displays details of waiting active queries.'],
      ['F DFHSM,Q REQ', 'Displays details of pending DFHSM requests.'],
      ['F DFHSM,Q WAIT', 'Displays details of tasks/requests waiting to execute.'],
      ['F DFHSM,REL ALL', 'Releases all active DFHSM tasks.'],
    ],
  },
  {
    title: '7. Useful MVS Commands',
    subtitle: 'General system commands for managing jobs, devices, and system resources.',
    headers: ['Command', 'Description'],
    rows: [
      ['D A,L,USERID=<ID>', 'Display active jobs for a given TSO userid'],
      ['D U,,,A80,16', 'Display from address A80 for 16 devices'],
      ['D U,VOL=<VOLSER>', 'Display the unit with this volume serial'],
      ['CANCEL JOB', 'Cancel a job'],
      ['CANCEL U=<USERID>', 'Cancel/force-off a TSO userid'],
      ['S <PROCLIB MEMBER>', 'Start a system job via a proclib member'],
      ['P <PROCLIB MEMBER>', 'Stop a system job (if it listens to STOP)'],
      ['P <JOBNAME>.<ID>,A=1234', 'Stop a specific job instance (e.g., P CICS.CICS1)'],
      ['SETPROG APF,ADD,DSN=<DSNAME>,VOLUME=<VOL>', 'Make a library APF-authorized (used when defining subsystems)'],
      ['D GRS,RES=(*)', 'Display GRS resources'],
      ['D GRS,RES=(SYSDSN)', 'Display enqueues on data set resources'],
      ['D GRS,C', 'List resources with contentions'],
      ['D GRS,E,C', 'List the resource everyone is waiting on'],
      ['D SSI', 'Display configured subsystems'],
      ['D SSI,SUB=<NAME>', 'Display information about a specific subsystem'],
        ['$D PROCLIB', 'Display the system procedure library'],
        ['DD CLEAR,DSN=ALL', 'Clear all SYS1.DUMP data sets'],
        ['DS QT,<addr>,<count>', 'Display tape device status (e.g., DS QT,483,1)'],
        ['D IOS,MIH,DEV=<addr>', 'Display MIH (Missing Interrupt Handler) timeout for a device'],
        ['V <addr>,ONLINE,UNCOND', 'Force a device online unconditionally (after offline/force boxed it)'],
        ['D LOGREC', 'Display LOGREC (error recording) data set status'],
        ['D PARMLIB', 'Display PARMLIB data sets specified at IPL'],
        ['D PROD,REGISTERED', 'Display registered software products'],
        ['D PROG,EXIT', 'Display program exits (CSV460I)'],
        ['D PROG,LNKLIST', 'Display LNKLST concatenation (CSV470I)'],
        ['D PROG,APF', 'Display APF-authorized libraries (CSV450I)'],
        ['D SMS', 'Display SMS configuration (SCDS, ACDS, COMMDS)'],
        ['D SYMBOLS', 'Display static system symbol values (&SYSCLONE, &SYSNAME, etc.)'],
        ['D U,IPLVOL', 'Display the IPL volume unit status'],
        ['F TSO,USERMAX=<n>', 'Set maximum number of TSO users (e.g., F TSO,USERMAX=1)'],
        ['M <dev>,VOL=(SL,<volser>),USE=PUBLIC', 'Mount a volume as public'],
        ['VARY CN(*),ACTIVATE', 'Activate the current console'],
        ['D C,HCONLY', 'Display hardcopy-only consoles'],
        ['DD ADD,DSN=<n>', 'Add a dump data set'],
        ['DD DEL,DSN=<n>', 'Delete a dump data set'],
        ['DUMP COMM=(<text>)', 'Take a system dump with description text'],
        ['Z EOD', 'Halt MVS and SMF (End of Day)'],
        ['S OMEGAMON', 'Start OMEGAMON monitoring'],
        ['P OMEGAMON', 'Stop OMEGAMON monitoring'],
        ['M <addr>,VOL=(SL,<volser>),USE=STORAGE', 'Mount a volume for storage use (tape mount)'],
        ['C <jobname>,DUMP', 'Cancel a job with a dump'],
        ['C <taskname>,DUMP', 'Cancel a task with a dump'],
        ['C <jobname>,A=<addr>', 'Cancel a job by address'],
        ['C U=<userid>,A=<addr>', 'Cancel a user by address'],
        ['FORCE <jobname>', 'Force a user job off the system'],
        ['FORCE <jobname>,A=<addr>', 'Force a job by address'],
        ['FORCE <userid>', 'Force a TSO user off'],
        ['FORCE <userid>,A=<addr>', 'Force a user by address'],
        ['RO <cmd>', 'Route command to send to sysplex members'],
        ['I SMF', 'Switch SMF data sets'],
        ["L '<text>'", 'Enter a comment into the system log'],
        ['MN <jobname(s)>,T', 'Display time and job name when a job starts/stops'],
        ['PA <dsname>', 'Add auxiliary storage to the system (page add)'],
        ["SE '<message>',SAVE", 'Put message in SYS1.BRODCAST for users on logon'],
        ['SE LIST', 'Display all messages in SYS1.BRODCAST'],
        ['SE <n>,DELETE', 'Delete a message from SYS1.BRODCAST'],
        ['SET CLOCK=hh.mm.ss', 'Set the system time'],
        ['SWAP <xxx>,<yyy>', 'Swap from device xxx to yyy'],
        ['V CN(*),DEACTIVATE', 'Deactivate HMC Operating System Messages console'],
        ['V CN(<n>),MSCOPE=<sys>', 'Set sysplex message traffic scope for a console'],
        ['E <jobname>,PERFORM=<n>', 'Change the performance level of a job'],
        ['E SWAP,<jobname>=NONSWAP', 'Set a job to nonswap status'],
        ['E SWAP,<jobname>=SWAP', 'Set a job to swappable status'],
        ['D U,,,<xxx>,1', 'Display boxed tape drive status'],
        ['V <xxx>,OFFLINE,FORCE', 'Force a tape drive offline (requires reply YES)'],
        ['V <xxx>,OFFLINE,UNCOND', 'Take a tape drive offline unconditionally'],
      ],
    },
    {
      title: '8. OMVS & UNIX System Services',
    subtitle: 'Commands for managing the UNIX System Services environment and filesystems.',
    headers: ['Command', 'Description'],
    rows: [
      ['D OMVS', 'Display whether OMVS is active'],
      ['D OMVS,F', 'Display mounted file systems'],
      ['D OMVS,OPTIONS', 'Display OMVS kernel options'],
      ['D OMVS,PFS', 'Display the file systems OMVS knows about'],
      ['F OMVS,PFS=ZFS,QUERY,STATUS', 'Query ZFS status (z/OS 2.2 or later)'],
      ['F OMVS,PFS=ZFS,QUERY,...', 'Display stats about ZFS (e.g., all,dataset,iobydasd,vm)'],
      ['CHMOUNT -W <path>', 'Change a file system to read/write'],
      ['CHMOUNT -R <path>', 'Change a file system back to read-only'],
    ],
  },
  {
    title: '9. VTAM (Virtual Telecommunications Access Method)',
    subtitle: 'Commands for managing VTAM network resources.',
    headers: ['Command', 'Description'],
    rows: [
      ['D NET,ID=<ID>', 'Display VTAM network resource status'],
      ['Z NET,QUICK', 'Quick shut down VTAM'],
      ['V NET,ACT,ID=<ID>', 'Activate a VTAM network resource'],
        ['V NET,INACT,ID=<ID>', 'Deactivate a VTAM network resource'],
        ['D NET,MAJNODES', 'Display VTAM major nodes'],
        ['Z NET', 'Take down VTAM normally (allows LU sessions to end normally)'],
        ['Z NET,CANCEL', 'Force take down VTAM when Z NET and Z NET,QUICK fail (kills everything)'],
        ['D NET,BFRUSE,BUFFER=SHORT', 'Display VTAM short buffer usage'],
        ['D NET,CDRMS', 'Display cross-domain resource managers'],
        ['D NET,LINES', 'Display information about VTAM lines'],
        ['D NET,PENDING', 'Display nodes in pending status'],
        ['D NET,PENDING,ID=<name>', 'Display IDs pending activation'],
        ['D NET,STATIONS', 'Display all VTAM stations'],
        ['D NET SESSIONS,LIST=ALL,MAX=500,E', 'Display all active VTAM sessions'],
        ['D NET,TSOUSER,ID=<userid>', 'Display TSO users connected via VTAM'],
        ['D NET,NETSRVR,E', 'Display network server status'],
        ['D NET,CLSTRS', 'Display VTAM clusters'],
        ['D NET,APPLS', 'Display VTAM applications'],
        ['D NET,ADJSSCPS,ADJLIST=*', 'Display adjacent SSCPs (subarea nodes)'],
        ['D NET,ROUTE,...', 'Display NCP routing information'],
        ['D NET,ADJCLUST,NETID=<name>', 'Display adjacent cluster'],
        ['D NET,ADJCP,ID=<name>,E', 'Display a specific adjacent CP'],
        ['F NET,TRACE,TYPE=IO,ID=<name>', 'Trace I/O on a VTAM line'],
      ],
    },
    {
      title: '10. Subsystem Commands (DB2, MQ)',
    subtitle: 'Commands for managing DB2, MQ, and other subsystems.',
    headers: ['Command', 'Description'],
    rows: [
      ["SETSSI ADD,S=<SSID>,I=<INI MEMBER>,INITPARM='<PARMS>'", 'Add a subsystem definition (MQ, DB2, etc.)'],
      ['%<SSID>', 'Start a queue manager (e.g., %CSQ9)'],
      ['-<SSID>', 'Start a DB2 subsystem (e.g., -DBCG)'],
      ['D SSI', 'List configured subsystems'],
      ['D SSI,SUB=<SSID>', 'Display details of a specific subsystem'],
      ['F <SSID>,...', 'Issue a command to a running subsystem'],
    ],
  },
  {
    title: '11. TCP/IP Commands',
    subtitle: 'Commands for managing TCP/IP stacks and network connections.',
    headers: ['Command', 'Description'],
    rows: [
      ['D TCPIP', 'List available TCP/IP stacks'],
      ['D TCPIP,<NAME>,NETSTAT,CONN', 'Display network connections for a specific TCP/IP stack'],
      ['D TCPIP,,NETSTAT,CONN', 'Display connections when only one TCP/IP stack exists'],
      ['D TCPIP,<NAME>,NETSTAT,HOME', 'Display IP addresses used by a TCP/IP stack'],
      ['V NET,ACT,ID=<LINE>', 'Activate a network line'],
      ['V NET,INACT,ID=<LINE>', 'Deactivate a network line'],
      ['F LLA,REFRESH', 'Refresh LLA (Link List Assembly)'],
    ],
  },
  {
    title: '12. JES2 Commands',
    subtitle: 'Commands for managing JES2 spool, initiators, printers, and job queues.',
    headers: ['Command', 'Description'],
    rows: [
      ['$D JES2', 'Display current JES2 activity (I/O, active address spaces, networking)'],
      ['$DI', 'Display initiators'],
      ['$DI1-5', 'Display initiators 1 through 5'],
      ['$PI2-3', 'Stop initiators 2 to 3'],
      ['$SI2-3', 'Start initiators 2 to 3'],
      ['$ADD PRT1,UNIT=<ADDR>', 'Add a printer with a specific unit address'],
      ['$DPRT*', 'Display all printers'],
      ['$DPRT1', 'Display printer 1'],
      ['$SPRT1', 'Start printer 1 (may need to issue twice)'],
      ['$PPRT1', 'Stop printer 1'],
      ['$DU,STA', 'Display which units (printers, etc.) are started'],
      ['$PJES2', 'Stop JES2 (after everything is quiesced)'],
      ["$DJOBCLASS('STC'),OUTDISP", 'Display output disposition for STC job class'],
      ['$T JOBCLASS(STC),OUTDISP=(,)', 'Set where STC output goes'],
      ['$DSPOOL', 'Display how full the spool is'],
      ['$D JOBDEF', 'Display number of JOEs (Job Output Elements)'],
      ['$T OUTDEF,JOENUM=<NUM>', 'Dynamically increase JOENUM limit'],
      ['$DJQ,SPL=(%>1)', 'Display jobs using more than 1% of spool'],
      ['$DS,SPL=(%>1)', 'Display STCs using more than 1% of spool'],
      ['$DT,SPL=(%>1)', 'Display TSO users using more than 1% of spool'],
      ['$DJQ,DAYS>2', 'Display jobs more than 2 days old'],
      ['$DO JQ,JM=<PREFIX>*', 'Display all output for jobs with a given prefix'],
      ['$PO JQ,JM=<PREFIX>*', 'Purge all output for jobs with a given prefix'],
      ['$DO JQ,AGE>4', 'Display output datasets more than 4 days old'],
      ['$PO JQ,AGE>4', 'Purge output datasets more than 4 days old'],
      ['$DO JQ,JM=<PREFIX>*,A>7', 'Display output for prefix older than 7 days'],
        ['$PO JQ,JM=<PREFIX>*,A>7', 'Purge output for prefix older than 7 days'],
        ['$DSPL,JOBS=<n>', 'Display all jobs using n% or more of spool (e.g., $DSPL,JOBS=5)'],
        ['$A A', 'Release all held jobs'],
        ['$ACTIVATE', 'Activate new functions at the current JES2 release level'],
        ['$ADD APPL', 'Dynamically define a VTAM application to JES2'],
        ['$ADD DESTID', 'Dynamically define a symbolic name for a JES2 route code'],
        ['$ADD FSS', 'Dynamically define a functional subsystem (FSS) to JES2'],
        ['$ADD LINE(<nnnn>)', 'Dynamically add a line'],
        ['$ADD LOGON(<nn>)', 'Create a new LOGON pseudo-device (defines JES2 as VTAM application)'],
        ['$ADD REDIRECT', 'Specify command redirection for an entry console'],
        ['$ADD RMT(<nnnn>)', 'Add one or more RJE workstations'],
        ['$C A', 'Cancel processing of all automatic command entries'],
        ['$C A <n>', 'Cancel auto job ID n (e.g., $C A 3)'],
        ['$D BUFDEF', 'Display current BUFDEF initialization parameter values'],
        ['$DQ', 'Display JES2 job queues and spool utilization'],
        ['$D SPOOLDEF', 'Display JES2 spooling environment characteristics'],
        ['$D U,LOGON1', 'Display LOGON1 unit status'],
        ['$D U,VOLSER=<volser>', 'Find the DASD address by volume serial'],
        ['$SSPL(<pool>),FORMAT', 'Format a JES2 spool partition (e.g., $SSPL(MPSPL2),FORMAT)'],
        ['$T <dev>.<id>,DISP=KEEP', 'Change output disposition to KEEP (e.g., $T OFF1.ST,DISP=KEEP)'],
        ['$T NODE(<name>),PATHMGR=NO', 'Disable path manager for a JES2 node'],
        ['$T A,ALL', 'Display all scheduled automatic commands'],
        [
          "$TA,I=<sec>,T=<time>,\\'$VS,\\'\\'<cmd>\\'\\'\\'",
          "Schedule an automatic command at interval (e.g., $TA,I=900,T=11.15,\\'$VS,\\'\\'D A,L\\'\\'\\')",
        ],
        ["$VS,\\'<cmd>\\'", "Issue a system command from JES2 startup (e.g., $VS,\\'V (234,235,236),OFFLINE\\')"],
        ['$DSPL,ALL', 'Display all spool volumes'],
        ['$D JOBQ,SPOOL=(%<n>)', 'Display jobs occupying more than n% of spool'],
        ['$DU,PRTx', 'Display printer x information'],
        ["$T '<jobname>',PRTY=<y>", 'Change a job priority'],
        ['$T Ix,C=<y>', 'Change class of an initiator'],
        ['$A <jobname>', 'Release a specific held job'],
        ['$E <jobname>', 'Restart a job'],
        ['$H <jobname>', 'Hold a specific job'],
        ['$P JES2,ABEND', 'Force bring down JES2 (abend)'],
        ['$DA', 'Display all active jobs'],
        ['$DA,T', 'Display all active TSO users'],
        ['$DA,S', 'Display all active started tasks'],
        ['$DN,Q=HOLD', 'Display jobs in HOLD status'],
        ['$DQ,V=SPOOL<n>', 'Display all jobs occupying a specific spool volume'],
        ['$D SPOOL,ALL', 'Display status of all spool volumes'],
        ['$SSPL,V=SPOOL<n>', 'Start a spool pack'],
        ['$SSPL,V=SPOOL<n>,FORMAT', 'Format and start a new spool volume'],
        ['$PSPL,V=SPOOL<n>', 'Drain a spool pack'],
        ['$DJ<nnnn>', 'Display a job by job number'],
        ["$DMJ<nnnn>,'<text>'", 'Send a message to the JCL of a job'],
        ['$DS<nn>', 'Display a started task by job number'],
        ['$DT<nn>', 'Display a TSO user by job number'],
        ['$DMASDEF', 'Display the MAS (Multi-Access Spool) environment'],
        ['$DNODE', 'Display all JES nodes'],
        ['$DNODE(<name>)', 'Display a specific JES node'],
        ['$SN,A=<name>', 'Start a JES node for an SNA line'],
        ['$CJ<nn>,D', 'Cancel a job by number with a dump'],
        ['$PJ<nn>', 'Purge a job by number'],
        ['$LJ<nn>', 'List output for a job by number'],
        ['$LS<nn>', 'List output for a started task by number'],
        ['$LT<nn>', 'List output for a TSO session by number'],
        ['$AJ<nn>-<nn>', 'Release a range of held job numbers'],
        ['$AS<n>', 'Activate a system job number'],
        ['$CJ<nn>,P', 'Cancel and purge a job'],
        ['$CS<n>', 'Cancel a system job'],
        ['$DA,L=A', 'Display active jobs on one system'],
        ['$DA,ALL,L=A', 'Display active jobs on all systems'],
        ['$DN,L=A', 'Display status of all jobs in the system'],
        ['$DN,Q=XEQ,L=A', 'Display jobs awaiting execution'],
        ['$DN,Q=PPU,L=A', 'Display jobs waiting to be printed or punched'],
        ['$DN,Q=HOLD,L=A', 'Display jobs in hold status'],
        ['$DN,R=<n>-<n>', 'Display names for a remote range'],
        ['$DQ,XEQ,L=A', 'Display queue for jobs awaiting execution'],
        ['$DQ,XEQ(<CLASS>),L=A', 'Display queue for jobs in a specific class'],
        ['$PLNE<nn>', 'Immediately stop activity on a line'],
        ['$O Q,ALL,A=<nn>,CANCEL', 'Cancel all held output nn days old or older'],
        ['$TNUM,BASE=1', 'Reset JOB numbers to 1'],
        ['$TI<nn>,<class>', 'Change initiator to input class'],
        ['$DU,RMT<#>', 'Display a remote'],
        ['$SRMT<#>', 'Start an individual remote'],
        ['$PRMT<#>', 'Drain an individual remote'],
        ['$DR<#>.PR1', 'Display a remote printer'],
        ['$SR<#>.PR1', 'Start a remote printer'],
        ['$PR<#>.PR1', 'Drain a remote printer'],
        ['$ER<#>.PR1', 'Restart a remote printer'],
        ['$NR<#>.PR1', 'Repeat a remote printer'],
        ['$CR<#>.PR1', 'Cancel a remote printer'],
        ['$TR<#>.PR1,Q=*', 'Set a remote printer output class'],
        ['$DN,Q=XEQ*', 'Display input queue for an individual class'],
        ['$DQ,R=<#>', 'Display number of queued jobs for a specific remote'],
        ['$DF', 'Display all output by form numbers'],
        ['$DF,R=<#>', 'Display all output for an individual remote'],
        ['$IPRT<#>', 'Interrupt a printer'],
        ['$ZPRT<#>', 'Halt a printer'],
        ['$BPRT<#>', 'Backspace a printer'],
        ['$FPRT<#>', 'Forward space a printer'],
        ['$TPRT<#>,F=*', 'Set printer form'],
        ['$TPRT<#>,LIM=*', 'Set printer line count limit'],
        ['$TPRT<#>,R=*', 'Set printer remote queue'],
        ['$TR<#>.CON,D=T', 'Alter a remote console to display time with job numbers'],
        ["$DMR<n>,'<message>'", 'Send a message to a remote'],
        ["$DMR<n>-<n>,'<message>'", 'Send a message to several remotes'],
        ['$H Q,ALL', 'Hold all job queues'],
        ['$A Q,ALL', 'Release all job queues'],
        ["$A Q,C='<class>'", 'Release a specific job class'],
        ["$H Q,C='<class>'", 'Hold a specific job class'],
      ],
    },
    {
      title: '13. z/OS File System (zFS) Commands',
    subtitle: 'Commands for managing zFS aggregates and file systems.',
    headers: ['Command', 'Description'],
    rows: [
      ['D OMVS,PFS', 'Display the file systems OMVS knows about'],
      ['F ZFS,QUERY,STATUS', 'Query ZFS status (not running under USS)'],
      ['F OMVS,PFS=ZFS,QUERY,STATUS', 'Query ZFS status (running under USS, z/OS 2.2+)'],
      ['F ZFS,FSINFO,ALL', 'Display detailed information about zFS aggregates'],
      ['F OMVS,PFS=ZFS,QUERY,...', 'Display ZFS stats (all, dataset, iobydasd, vm, etc.)'],
      ['ZFSADM CONFIGQUERY', 'Display current ZFS configuration values'],
      ['ZFSADM CONFIG...', 'Change ZFS configuration parameters'],
      ['ZFSADM AGGRINFO <DSNAME>', 'Display size and info of a zFS aggregate'],
      ['ZFSADM GROW -AGGREGATE <DSNAME> -SIZE <KB>', 'Increase the size of a zFS aggregate'],
    ],
  },
  {
    title: '14. TSO/ISPF Commands',
    subtitle: 'Useful TSO and ISPF commands for dataset and member management.',
    headers: ['Command', 'Description'],
    rows: [
      ['DDLIST or ISRDDN', 'Display TSO allocations (useful for ISPPLIB concatenation)'],
      ['Line cmd: B', 'Browse the first sixteen datasets or a single dataset'],
      ['Line cmd: E', 'Edit the first sixteen datasets or a single dataset'],
      ['Line cmd: V', 'View the first sixteen datasets or a single dataset'],
      ['Line cmd: M', 'Show an enhanced member list'],
      ['Line cmd: F', 'Free the entire DDNAME'],
      ['Line cmd: C', 'Compress a PDS using existing allocation'],
      ['Line cmd: I', 'Provide additional dataset information'],
      ['Line cmd: Q', 'Display list of users or jobs using a dataset'],
      ['Prim cmd: FIND', 'Find a string in the dataset'],
      ['Prim cmd: LOCATE', 'Locate a member name'],
      ['Prim cmd: SORT', 'Sort the member list'],
      ['Prim cmd: RESET', 'Reset the display'],
      ['MOUNT FILESYSTEM(<DSNAME>) MOUNTPOINT(<PATH>) TYPE(ZFS) MODE(READ)', 'Mount a zFS filesystem'],
      ['UNMOUNT FILESYSTEM(<DSNAME>) NORMAL', 'Unmount a zFS filesystem'],
      ['WHOIS <userid|name>', 'Find TSO user information'],
    ],
  },
  {
    title: '15. RACF Security Commands',
    subtitle: 'Commands for managing RACF security, user IDs, and profiles.',
    headers: ['Command', 'Description'],
    rows: [
      ['AU / ADDUSER', 'Add a new RACF user with TSO parameters (DFLTGRP, OWNER, PASSWORD, TSO)'],
      ['DU / DELUSER', 'Delete a RACF user'],
      ['ALU / ALTUSER', 'Alter a RACF user (change DFLTGRP, OWNER, NAME, etc.)'],
      ['ALU <USER> PASSWORD(<pass>)', 'Reset a RACF user password'],
      ['ALU <USER> RESUME', 'Resume a revoked RACF user'],
      ['ALU <USER> REVOKE', 'Revoke a RACF user'],
      ['ALU <USER> NOOMVS', 'Remove OMVS/USS access from a user'],
      ['ALU <USER> HOME(<path>) PROGRAM(<shell>) AUTOUID', 'Grant OMVS/USS access to a user'],
      ['AG / ADDGROUP', 'Add a new RACF group with SUPGROUP (superior group)'],
      ['DG / DELGROUP', 'Delete a RACF group'],
      ['CONNECT <USER> GROUP(<GROUP>)', 'Connect a user to a RACF group'],
      ['REMOVE <USER> GROUP(<GROUP>)', 'Remove a user from a RACF group'],
      ['RDEFINE / RDEF', 'Define a RACF general resource or dataset profile'],
      ['RDEFINE <CLASS> <PROFILE> ADDMEM(...)', 'Define a resource group profile with members'],
      ['RALTER <CLASS> <PROFILE> <ATTR>', 'Change a RACF profile (e.g., RALTER class profile UACC(READ))'],
      ['RDELETE <CLASS> <PROFILE>', 'Delete a RACF profile'],
      ['PERMIT <PROFILE> CLASS(<CLASS>) ID(<USER>) ACCESS(<LEVEL>)', 'Permit a user/group to a resource'],
      ['PERMIT <PROFILE> CLASS(<CLASS>) ID(<USER>) DELETE', 'Remove a user/group from access list'],
      ['PERMIT ... FROM(<PROFILE>) FCLASS(<CLASS>)', 'Copy access list from another profile'],
      ['RLIST <CLASS> <PROFILE> AUTHUSER', 'List authorized users for a profile'],
      ['SEARCH CLASS(<CLASS>)', 'List all profile names in a class'],
      ['SETROPTS CLASSACT(<CLASS>)', 'Activate RACF protection for a class'],
      ['SETROPTS NOCLASSACT(<CLASS>)', 'Deactivate RACF protection for a class'],
      ['SETROPTS GENERIC(<CLASS>)', 'Enable generic profile support for a class'],
      ['SETROPTS PASSWORD(MIXEDCASE)', 'Enable or disable mixed-case passwords'],
      ['SETROPTS LIST', 'Display currently active RACF classes'],
      ['SETR RACLIST(<CLASS>) REFRESH', 'Refresh RACF in-storage profiles'],
      ['RVARY', 'Display/list RACF datasets (operator command #RVARY)'],
      ['#SET TRACE(...)', 'Turn on/off RACF trace to GTF'],
      ['AD / ADDSD <HLQ.*> UACC(NONE)', 'Define a dataset HLQ profile'],
      ['DEFINE ALIAS(NAME(<alias>) RELATE(<catalog>))', 'Define a catalog alias for a user HLQ (IDCAMS)'],
      ['RDEF JESJOBS SUBMIT|CANCEL <pattern>', 'Define JESJOBS profile for submit/cancel authorization'],
      ['LD DA(<dataset>) GEN', 'Display which RACF profile protects a dataset'],
      ['LU <USER>', 'List RACF user information and attributes'],
      ['LG <GROUP>', 'List RACF group information'],
    ],
  },
  {
    title: '16. SDSF Commands',
    subtitle: 'Commands and shortcuts for using SDSF (System Display and Search Facility).',
    headers: ['Command', 'Description'],
    rows: [
      ['OWNER <USERID>', 'Show jobs owned by a specific user'],
      ['PREFIX <NAME>', 'Display jobs beginning with a prefix'],
      ['SYSNAME <NAME>', 'View jobs on another connected system'],
      ['FILTER <CRITERIA>', 'Filter on multiple criteria (e.g., owner eq PAICE, jobname eq MQ*)'],
      ['SORT <COLUMN>', 'Sort by a column (e.g., sort cpu%)'],
      ['ARRANGE <COL> <DIRECTION>', 'Rearrange column display order'],
      ['Prefix: S', 'Display the spool output'],
      ['Prefix: SE', 'Display in edit mode'],
      ['Prefix: C', 'Cancel the job (issues JES CANCEL)'],
      ['Prefix: ?', 'Display available output files within the job'],
      ['Prefix: SJ', 'Edit the JCL and resubmit the job'],
      ['LOG S', 'Display system message log for this MVS system'],
      ['LOG O', 'Display merged sysplex-wide system message log'],
      ['ULOG', 'Display output from commands you have issued'],
        ['ST', 'Shortcut ST command (used instead of DA, O, etc.)'],
        ['Prefix: XDC', 'Save job output as a dataset (displays a self-explaining menu, job stays in output queue)'],
        ['DA OJOB', 'Display jobs currently running (SDSF)'],
        ['SYSID <xxxx>', 'Switch to another syslog in SDSF'],
      ],
    },
    {
      title: '17. MQ Series Commands',
    subtitle: 'Commands for managing IBM MQ queue managers and channels.',
    headers: ['Command', 'Description'],
    rows: [
      ["ALTER QMGR CHLAUTH(DISABLED) CONNAUTH(' ')", 'Turn off MQ channel init connection security checking'],
      ['REFRESH SECURITY(*) TYPE(CONNAUTH)', 'Tell MQ to pick up security changes'],
    ],
  },
    {
      title: '18. SMF (System Management Facility) Commands',
      subtitle: 'Commands for managing SMF recording and intervals.',
      headers: ['Command', 'Description'],
      rows: [
        ['SETSMF INTVAL(01)', 'Change how often SMF drives end of interval'],
        ['SETSMF MAXDORM(0010)', 'Set max time SMF keeps data in buffer before writing out'],
      ],
    },
    {
      title: '19. DFSMS (Data Facility Storage Management Subsystem)',
      subtitle: 'Commands for managing DFSMS catalog caching and performance.',
      headers: ['Command', 'Description'],
      rows: [
        ['F CATALOG,REPORT,CACHE', 'Report caching statistics for CDSC (VLF) and ISC catalog caching'],
        ['F CATALOG,REPORT,PERFORMANCE', 'Report counts and average elapsed time for catalog events'],
        ['F CATALOG,LIST(<id>)|LISTJ(<jobname>) DETAIL', 'Display detailed CAS request info including ENQs and locks'],
      ],
    },
    {
      title: '20. TSO/E Commands',
      subtitle: 'Useful TSO/E and diagnostic commands.',
      headers: ['Command', 'Description'],
      rows: [
        ['SYNC', 'Initialize SYS1.BRODCAST and synchronize with RACF dataset or SYS1.UADS'],
        ['SHOWMVS', 'Display system info (CBT tape tool by Gilbert Saint-flour, from ISPF option 6)'],
      ],
    },
    {
      title: '21. VLF (Virtual Lookaside Facility)',
      subtitle: 'Commands for managing the Virtual Lookaside Facility catalog caching.',
      headers: ['Command', 'Description'],
      rows: [
        ['F CATALOG,REPORT,CACHE', 'Determine which catalogs are in VLF caching'],
        ['F CATALOG,NOVLF(<catalog.name>)', 'Remove a catalog from VLF caching'],
      ['', 'Remember to update changes in SYS1.PARMLIB(COFVLFxx)'],
    ],
  },
  {
    title: '23. CICS (Customer Information Control System)',
    subtitle: 'Commands for starting, stopping, and managing CICS regions.',
    headers: ['Command', 'Description'],
    rows: [
      ['S CICS***', 'Start a CICS region normally'],
      ['S CICS***,START=COLD', 'Cold start a CICS region'],
      ['S CICS***,START=INIT', 'Initial start of a CICS region'],
      ['F CICS***,CEMT P SHUT', 'Shut down CICS normally'],
      ['F CICS***,CEMT P SHUT IMM', 'Shut down CICS immediately (force)'],
      ['F CICS***,CEMT I CONN ALL', 'Display subsystems connected to CICS'],
      ['F CICS***,CEMT P SHUT I', 'Stop the CICS subsystem'],
      ['F <region>,CEMT I DU', 'Display CICS dump data set'],
      ['F <region>,CEMT I SYS', 'Display system and net name'],
      ['F <region>,CEMT I Q', 'Display queues'],
      ['F <region>,CEMT I MAX', 'Display max tasks'],
      ['F <region>,CEMT I VTA', 'Display VTAM status'],
      ['F <region>,CEMT I TAS', 'Display tasks'],
      ['F <region>,CEMT I TRAN', 'Display transactions'],
      ['F <region>,CEMT I DA(<dsn>)', 'Display data set'],
      ['F <region>,CEMT I NE(<term>)', 'Display network for terminal'],
      ['F <region>,CEMT PERFORM SHUT', 'Shut down a CICS region'],
      ['F <region>,CEMT S TE(<term>) ACQ', 'Acquire terminal to CICS'],
      ['F <region>,CEMT S TE(<term>) REL', 'Release terminal from CICS'],
      ['F <region>,CEMT S TE(<term>) INS', 'Put terminal in service'],
      ['F <region>,CEMT S TE(<term>) OUT', 'Take terminal out of service'],
      ['F <region>,CEMT S DUMP,CLOSE', 'Close dump data set'],
      ['F <region>,CEMT S Q', 'Set queue options (All, Enable/Disable, Open/Close)'],
      ['F <region>,CEMT S AMAX(<n>) MAX(<n>)', 'Set AMAX and MAX tasks'],
      ['F <region>,CEMT S TRAN(<n>) DIS', 'Disable a transaction'],
      ['F <region>,CEMT S TAS(<n>) PU', 'Purge a task'],
      ['F <region>,CEMT S TAS(<n>) FORCE', 'Force a task'],
      ['F <region>,CEMT S PROG(<name>) ENA', 'Enable a program'],
      ['F <region>,CEMT S PROG(<name>) ENA NEW', 'Enable and copy a new program'],
      ['F <region>,CEMT S NE(<n>) FORCE', 'Force a netname'],
      ['F <region>,CEMT S NE(<n>) PURGE', 'Purge a netname'],
      ['F <region>,CEMT S NE(<n>) OUT', 'Take a device out of service'],
      ['F <region>,CEMT S NE(<n>) IN', 'Put a device in service'],
      ['F <region>,CEMT S VTAM CLO', 'Close VTAM to CICS region'],
      ['F <region>,CEMT S VTAM OPE', 'Open VTAM to CICS region'],
      ['F <region>,CEMT TRMNAT,TERMID=<id>', 'Terminate task and put terminal out of service'],
      ['F <region>,CEMT TRACE,ON', 'Start trace'],
      ['F <region>,CEMT ATR,ON', 'Enable auxiliary trace'],
      ['F <region>,CEMT ATR,ATC', 'Close auxiliary trace file'],
      ['F <region>,CEMT SWITCH', 'Switch dump data set'],
      ['F <region>,CEMT SNAP', 'Issue a snap dump'],
    ],
  },
  {
    title: '24. DB2 (Database 2) Commands',
    subtitle: 'Commands for starting, stopping, and monitoring DB2 subsystems.',
    headers: ['Command', 'Description'],
    rows: [
      ['XSTARTDB2', 'Start DB2 subsystem'],
      ['XSTOPDB2', 'Stop DB2 subsystem'],
      ['XDIS THD(*)', 'Display all threads in DB2'],
      ['XDIS UTIL(*)', 'Display all utilities in DB2'],
      ['-DSNx DISPLAY DATABASE', 'Display the status of a database'],
      ['-DSNx DISPLAY THREAD(*)', 'Display thread information for DB2 program connections'],
      ['-DSNx DISPLAY TRACE', 'Display the status of DB2 traces'],
      ['-DSNx DISPLAY LOCATION', 'Display DDF information'],
      ['-DSNx DISPLAY UTILITY(*)', 'Display the status of a utility'],
      ['-DSNx START DATABASE', 'Start databases or tablespaces'],
      ['-DSNx START TRACE', 'Start DB2 trace'],
      ['-DSNx STOP DATABASE', 'Stop databases or tablespaces'],
      ['-DSNx STOP TRACE', 'Stop trace'],
      ['-DSNx TERM UTILITY', 'Terminate execution of a utility'],
      ['-DSNxSTART DB2 PARM(<parms>)', 'Start DB2 on the LPAR'],
      ['-DSNxSTOP DB2', 'Stop DB2 on the LPAR'],
    ],
  },
  {
    title: '25. IDMS (Integrated Database Management System)',
    subtitle: 'Commands for managing IDMS sessions and resources.',
    headers: ['Command', 'Description'],
    rows: [
      ['NN 99SIGNON <userid> <password>', 'Sign on to IDMS from the console'],
      ['NN 99BYE', 'Sign off from IDMS'],
      ['DCUF SHOW USERS ALL', 'Show all IDMS users'],
      ['DCMT DIS ACT TASKS', 'Display active IDMS tasks'],
      ['DCMT D PRI', 'Display IDMS printers'],
    ],
  },
  {
    title: '26. WLM (Workload Manager) Commands',
    subtitle: 'Commands for managing workload classes and service levels.',
    headers: ['Command', 'Description'],
    rows: [
      ['$D JOBCLASS(*)', 'Display all job classes'],
      ['$D JOBCLASS(<a>,<b>)', 'Display specific job classes'],
      ['$T JOBCLASS(*),QHELD=Y', 'Hold all job classes'],
      ['$T JOBCLASS(*),QHELD=N', 'Release all job classes'],
      ['F LLA,REFRESH', 'Refresh LLA'],
      ['SE \'<message>\'', 'Send message to all TSO users'],
      ['SE \'<message>\',USERID=<id>', 'Send message to a specific TSO user'],
      ['G <dev1>,<dev2>', 'Swap tape volumes'],
    ],
  },
  {
    title: '27. MIMS Tape Drive Commands',
    subtitle: 'Commands for managing tape drive availability across LPARs.',
    headers: ['Command', 'Description'],
    rows: [
      ['@D G,<xxx>,#', 'Display status of specified tape drives'],
      ['@V <xxx>,NOTAVL,G', 'Vary drive not available on all LPARs'],
      ['@V <xxx>,OVER,G', 'Reset device status to undefined on all LPARs'],
      ['@V <xxx>,AVL,L', 'Vary drive available on local system and online to MVS'],
      ['@V <xxx>,AVL,G', 'Vary drive available on all LPARs'],
      ['@V <xxx>,NOTOVER,G', 'Reset device status to defined/known on all LPARs'],
    ],
  },
  {
    title: '28. IMS (Information Management System) Commands',
    subtitle: 'Commands for managing IMS transactions, regions, and subsystems.',
    headers: ['Command', 'Description'],
    rows: [
      ['DIS A', 'Display active tasks on IMS'],
      ['/STA TRAN <xxxx>', 'Start an IMS transaction'],
      ['/STO TRAN <xxxx>', 'Stop an IMS transaction'],
      ['STA REG <xx>', 'Start IMS regions'],
      ['/STO REG <xxx>,ABEND', 'Cancel a job/region on IMS'],
      ['/DIS SUBSYS ALL', 'Display DB2 connections to IMS'],
      ['/STA SUBSYS DB2X', 'Start DB2 connections for IMS'],
      ['/DIS CCTL', 'Display status for IMS to CICS connection'],
      ['/DIS DB ALL', 'Display all databases'],
      ['/DIS DB <dbd-name>', 'Display specific database(s)'],
      ['/DIS TRAN ALL', 'Display all transactions'],
      ['/DIS TRAN <tran-name>', 'Display specific transaction(s)'],
      ['/DIS PGM ALL', 'Display all programs'],
      ['/DIS PGM <pgm-name>', 'Display specific program(s)'],
      ['/DIS NODE <node-name>', 'Display specific node(s)'],
      ['/DIS LTERM <lterm-name>', 'Display specific logical terminal(s)'],
      ['/DIS ASMT NODE <node-name>', 'Display lterms assigned to node'],
      ['/DIS ASMT LTERM <lterm-name>', 'Display node assigned to lterm'],
      ['/DIS STATUS DB', 'Display stopped/inactive databases'],
      ['/DIS STATUS PGM', 'Display stopped/inactive programs'],
      ['/DIS STATUS TRAN', 'Display stopped/inactive transactions'],
      ['/DIS Q TRAN', 'Display all transactions to be processed'],
      ['/RCL', 'Log off IMS'],
    ],
  },
]

export default function ConsoleCommands() {
  return (
    <div className="min-h-screen bg-black pt-24 pb-16 px-4 sm:px-6 lg:px-8">
      <div className="max-w-6xl mx-auto">
        <div className="text-center mb-12">
          <h1 className="text-3xl sm:text-4xl md:text-5xl font-playfair italic text-white mb-4">
            z/OS Mainframe Commands Reference Guide
          </h1>
           <p className="text-white/60 text-sm sm:text-base max-w-3xl mx-auto leading-relaxed">
            A comprehensive quick-reference guide for z/OS Mainframe commands compiled and transcribed from reference documents. This includes Display (D), Console Control (K), Vary (V), Storage (DFHSM, DASD/Tape), MVS, OMVS, VTAM, TCP/IP, JES2, zFS, TSO/ISPF, RACF, SDSF, MQ, SMF, and subsystem commands.
          </p>
        </div>

        {sections.map((section, idx) => (
          <div key={idx} className="mb-12">
            <h2 className="text-xl sm:text-2xl font-semibold text-white mb-2">{section.title}</h2>
            <p className="text-white/50 text-sm mb-6">{section.subtitle}</p>

            <div className="overflow-x-auto rounded-xl border border-white/10">
              <table className="w-full text-sm text-left">
                <thead>
                  <tr className="bg-white/10">
                    {section.headers.map((header, i) => (
                      <th key={i} className="px-4 py-3 text-white font-semibold whitespace-nowrap">
                        {header}
                      </th>
                    ))}
                  </tr>
                </thead>
                <tbody>
                  {section.rows.map((row, ri) => (
                    <tr key={ri} className="border-t border-white/5 hover:bg-white/5 transition-colors">
                      {row.map((cell, ci) => (
                        <td
                          key={ci}
                          className={`px-4 py-2.5 text-white/80 ${ci === 0 ? 'font-mono text-[#e8702a] whitespace-nowrap' : 'text-white/70'}`}
                        >
                          {cell}
                        </td>
                      ))}
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </div>
        ))}
      </div>
    </div>
  )
}
